### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by juiceluqi** [Frago9876543210/EasyForms#1]
HOW DO I USE THAT IN MY PLUGINS?

**Comment by Frago9876543210** [comment]
You need download it and see code samples from [README](https://github.com/Frago9876543210/EasyForms/blob/master/README.md)

**Comment by juiceluqi** [comment]
example: 

public function onDataPacket(DataPacketReceiveEvent $event) {
		$packet = $event->getPacket();
		$player = $event->getPlayer();
EasyForms::$settings = new ServerSettingsForm("Server settings", [
		new Label("Some text"),
		new class("Mute chat") extends Toggle{
			public function handle(Player $player, $value) : void{
				$player->sendMessage($value ? "enabled" : "disabled");
			}
		}
	]
);

Can I make a code like this?
