### ISSUE TITLE
Special Symbols missing

### ISSUE THREAD

**Issue by OverTook** [Frago9876543210/EasyForms#12]
```
$a = 1111;
$b = 2222;
$c = 3333;
$d = 4444;
EasyForms::sendForm($player, new class("Test", "Test for me.\n\n" . 
        "Your Name : " . $a . "-" . $b . "-" . $c . "-" . $d . "\n\n" . 
        "If right Click [Y], or [N].\nSry for my bad eng.", "y", "n") extends ModalForm{
              public function onSubmit(Player $player, $response) : void{
                     if(!$response){
                        $player->sendMessage("§8[ §7§lAlert §r§8] §rThx.");
                        return;
                     }
                     $player->sendMessage("§8[ §7§lAlert §r§8] §rThx2"); 
              }
});
```

I expected the following.
> Test for me.
> 
> Your Name : 1111-2222-3333-4444
> 
> If right Click [Y], or [N].
> Sry for my bad eng.

But this is what we actually received.

> Test for me.
> 
> Your Name
> 
> If right Click Y, or N.
> Sry for my bad eng.

Where did the following characters disappear?

> [ ]  : -

sorry for my bad eng 👍

**Comment by Frago9876543210** [comment]
Maybe client side bug

**Comment by Frago9876543210** [comment]
Works for me
![default](https://user-images.githubusercontent.com/13465245/44309472-f3e18100-a3cf-11e8-8517-79688d0f60a2.png)
