### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Shelly7w7** [Frago9876543210/EasyForms#18]
```[Server thread/CRITICAL]: ErrorException: "Declaration of class@anonymous::onSubmit(CastiaCore\events\Player $player, $response): void should be compatible with Frago9876543210\EasyForms\forms\CustomForm::onSubmit(pocketmine\Player $player, $response): void" (EXCEPTION) in "CastiaCore/src/CastiaCore/events/EventListener" at line 133```

**Comment by Frago9876543210** [comment]
Because there must be `pocketmine\Player` instead of `CastiaCore\events\Player`
Maybe you forget include that's class?

**Comment by Shelly7w7** [comment]
oh my bad, thnx
