### ISSUE TITLE
Add an API for adding elements after form creation

### ISSUE THREAD

**Issue by lukeeey** [Frago9876543210/EasyForms#20]
i want to show certain buttons if the player has a certain rank. I can't do this currently as elements are set in the constructor.

**Comment by Frago9876543210** [comment]
Now you can do something like this:
![изображение](https://user-images.githubusercontent.com/13465245/54882940-810e1c00-4e70-11e9-97f7-0718f3b14038.png)

**Comment by Frago9876543210** [comment]
Use append
