### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by CallMeYuuuu** [Frago9876543210/EasyForms#24]
Can anyone send me the download link please?

**Comment by Frago9876543210** [comment]
Using poggit

**Comment by Frago9876543210** [comment]
https://poggit.pmmp.io/ci/Frago9876543210/EasyForms/EasyForms

**Comment by CallMeYuuuu** [comment]
Thanks

Frago9876543210 <notifications@github.com> schrieb am Do., 1. Aug. 2019,
18:17:
