### ISSUE TITLE
Downloadlink API 4.0.0 PLEASE

### ISSUE THREAD

**Issue by CallMeYuuuu** [Frago9876543210/EasyForms#25]
Can anyone send me pleas the download link for the API version 4.0.0 of the EasyForms Pocketmine Plugin!
Thanks

**Comment by artulloss** [comment]
The master branch is the 4.0.0 version of the plugin.

**Comment by CallMeYuuuu** [comment]
But my rcon says that i need 4.0.0 with the plugin and i tooked the master branch
