### ISSUE TITLE
NOT A GUI!

### ISSUE THREAD

**Issue by NopeNotDark** [Frago9876543210/EasyForms#27]

**Comment by IceCruelStuff** [comment]
Its basically the same thing. [GUI](https://www.google.com/search?q=what+is+gui&oq=what+is+gui&aqs=chrome..69i57.2528j0j1&sourceid=chrome&ie=UTF-8), [UI](https://www.google.com/search?q=what+is+ui&oq=what+is+ui&aqs=chrome..69i57.6670j0j1&sourceid=chrome&ie=UTF-8)

**Comment by NopeNotDark** [comment]
nope not GUI is for Chest interface UI is for FormInterface

**Comment by IceCruelStuff** [comment]
Ok you're right

**Comment by ghost** [comment]
Graphical User Interface  
vs  
User Interface  
i dont get it is this supposed to be a joke??????!?!
