### ISSUE TITLE
How to make multiple buttons in MenuForm?

### ISSUE THREAD

**Issue by BlueWhaleYT** [Frago9876543210/EasyForms#29]
Hi there,
I finally figured out how does it work.
I am confusing how to make multiple buttons in Menu Form.
It means "A" button will sendMessage("Hello") ; "B" button will sendMessage("Hi")

I know how to make "two" buttons.
but the two button are showing same message.

Does it possible to implement it?

Thanks a lot.

**Comment by Frago9876543210** [comment]
`$selected->getValue()` will return index of pressed button started at 0

**Comment by BlueWhaleYT** [comment]
Oh!I see! Thanks a lot.!
